"""fix: add sale_item and config

Revision ID: 86888c7b64fb
Revises: ef5a0881d07d
Create Date: 2025-11-15 14:09:39.485159
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86888c7b64fb'
down_revision = 'ef5a0881d07d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('sales', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_foreign_key(None, 'sales', 'books', ['book_id'], ['id'])
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'book_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'])
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
